#!/usr/bin/env python3
"""Generate a fixed-point -log(x) lookup table as a C header.

This table lets ClapEngine's grain scheduler evaluate the Poisson-process
interonset formula from Ross Bencina's "Implementing Real-Time Granular
Synthesis" (interonsetTime = -log(frandom()) / density) entirely with
integer arithmetic, using mu_stmlib::Interpolate824() the same way
lut_env_expo/lut_svf_cutoff/etc. are used elsewhere in this codebase:

    uint32_t neg_log_fixed =
        mu_stmlib::Interpolate824(lut_neg_log, Random::GetWord());

Random::GetWord() already returns a uniform uint32_t, and Interpolate824()
reads the top 8 bits as a table index and the next 24 bits as the linear
interpolation fraction -- so the raw random word can be fed straight in as
the "phase" argument, no separate frandom()/scaling step needed.

Table layout: (size + 1) entries (the extra one is the interpolation
guard entry Interpolate824 reads at table[index + 1] when index ==
size - 1). Entry i (0 <= i < size) holds -log((i + 0.5) / size) so the
domain never includes x == 0 (which would make -log(x) diverge to
infinity). The guard entry re-uses the last value, which only affects the
extreme low-probability tail. Values are stored as fixed-point uint16_t,
scaled by --scale (default 4096, i.e. Q4.12).

Usage:
    python Scripts/generate_neg_log_lut.py
    python Scripts/generate_neg_log_lut.py --size 256 --scale 4096
    python Scripts/generate_neg_log_lut.py -o lut_neg_log.h

The .h file is written into the current working directory (the folder the
script is invoked from), not into Scripts/ itself.
"""

import argparse
import math
import os
import sys


def build_table(size: int, scale: int) -> list:
    """Returns size + 1 fixed-point -log(x) samples (see module docstring)."""
    table = []
    for i in range(size):
        x = (i + 0.5) / size
        value = round(-math.log(x) * scale)
        table.append(value)
    table.append(table[-1])  # interpolation guard entry
    return table


def format_table(values: list, per_line: int = 8) -> str:
    lines = []
    for start in range(0, len(values), per_line):
        chunk = values[start:start + per_line]
        lines.append("    " + ", ".join(f"{v:6d}" for v in chunk) + ",")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a fixed-point -log(x) LUT header for "
                    "ClapEngine's grain interonset-time computation.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--size", type=int, default=256,
        help="Number of table entries before the interpolation guard "
             "entry (default: 256, must be a power of two so "
             "Interpolate824's 8-bit index selects it cleanly).",
    )
    parser.add_argument(
        "--scale", type=int, default=4096,
        help="Fixed-point scale factor applied to -log(x) (default: 4096, "
             "i.e. Q4.12). Must leave headroom below 65535 for the "
             "largest table value (~6.24 * scale for size=256).",
    )
    parser.add_argument(
        "--array-name", default="lut_neg_log",
        help="Name of the generated C array (default: lut_neg_log).",
    )
    parser.add_argument(
        "-o", "--output", default=None,
        help="Output header file name (default: <array-name>.h), written "
             "into the current working directory.",
    )
    args = parser.parse_args()

    if args.size <= 0 or (args.size & (args.size - 1)) != 0:
        parser.error("--size must be a positive power of two")
    if args.scale <= 0:
        parser.error("--scale must be positive")

    table = build_table(args.size, args.scale)
    max_value = max(table)
    if max_value > 0xFFFF:
        parser.error(
            f"largest table value ({max_value}) overflows uint16_t -- "
            f"reduce --scale (try <= {int(0xFFFF / (max_value / args.scale))})"
        )

    output_name = args.output or f"{args.array_name}.h"
    output_path = os.path.join(os.getcwd(), output_name)

    guard_name = "_".join(
        ch if ch.isalnum() else "_" for ch in output_name.upper()
    )

    header = f"""// Auto-generated by Scripts/generate_neg_log_lut.py -- do not edit by hand.
//
// Fixed-point lookup table for -log(x), sampled at x = (i + 0.5) / {args.size}
// for i in [0, {args.size}), scaled by {args.scale} (values are -log(x) * {args.scale},
// rounded to the nearest integer). A final guard entry duplicates the last
// sample so mu_stmlib::Interpolate824() can safely read one entry past the
// last real sample.
//
// Intended use (see ClapEngine's grain interonset-time computation, after
// Ross Bencina's "Implementing Real-Time Granular Synthesis"):
//
//   uint32_t neg_log_fixed =
//       mu_stmlib::Interpolate824({args.array_name}, Random::GetWord());
//   uint32_t interonset_samples =
//       (neg_log_fixed * mean_interonset_samples) >> {int(args.scale).bit_length() - 1};
//
#pragma once

#include <cstdint>

const uint16_t {args.array_name}[] = {{
{format_table(table)}
}};
"""

    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)

    print(f"Wrote {len(table)} entries ({args.size} + 1 guard) to {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
